server:
  port: 8089
spring:
  application:
    name: order-service  # 服务名称
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka   # eureka中拉取服务列表
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1  # 保证获取到的地址是ip地址，而不是host
mybatis:
  type-aliases-package: com.lingxiao.pojo
ly:
  jwt:
    pubKeyPath: D:\\rsakey\\rsa.pub  # 公钥地址
    cookieName: LEYOU_COOKIE # cookie的名字
  worker:
    workerId: 1
    datacenterId: 1
  pay:
    appID: wx8397f8696b538317
    mchID: 1473426802
    key: T6m9ik73b0kn9g5v42MKfHQH7X8rKwb
    httpConnectTimeoutMs: 1000
    httpReadTimeoutMs: 8000
    notifyUrl: http://lingxiao.xiaomy.net/notify/pay